export const sectorConstants = {
  nameRegex: /^[a-zA-Z0-9.,\-_$/:[\]' '!]+$/,
  fileSize: 1024,
  fileCount: 1,
  width: 24,
  height: 24,
  duration: 2000,
  offset: 0,
  limit: 24,
  fileTypeRegex: /image\/*/,
  minCompatibilityLevel: 1,
  maxCompatibilityLevel: 2,
  zero: 0,
  pageSize: 20,
  pageOptions: [20, 30, 40],
}
